### ISSUE TITLE
Add color variables with formatting from Brand Guidelines

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#11]
The colors have a naming format in the Brand Guidelines, as [color]-100 to 1000. 
Blue, Pink and Yellow should be added as: "clr-blue-100" for every color and value, for ease of use later. ☺

The gray colors can also be added this way. They're not in the guidelines but these are the values:
100: #F0F0F0
200: #E2E2E2
300: #C6C6C6
400: #ABABAB
500: #909090
600: #767676
700: #5E5E5E
800: #464646
900: #303030
1000: #1B1B1B

**Comment by jolofren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add color variables with formatting from Brand Guidelines](https://trello.com/c/KWgyrvI2/19-add-color-variables-with-formatting-from-brand-guidelines)

**Comment by j-wiren** [comment]
This was solved some time ago
