### ISSUE TITLE
Banner Design Change proposal

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#161]
Known issues:

- On mobile the logo on the banner is too large and is overlapping with the banner border. 
- The old design is gone.

Should we try to experiment with this a little bit and see if we can re-establish the old design?

**Comment by j-wiren** [comment]
Yes, if we have time. There are other things that are higher priority, but if you have time for it afterwards it would be nice.

**Comment by olehoef** [comment]
This section will be redesigned.
