### ISSUE TITLE
Uneven styling between different companies info boxes

### ISSUE THREAD

**Issue by lundellstef** [Systemvetardagen/systemvetardagen.se#216]
Make styling behaviour coherent on all the different company info boxes.
For example: one company with only a few lines of information will display differently from another company with more lines of information.

**Comment by lundellstef** [comment]
I think issue is with the div on line 61 in companies.vue
div on 61, with company "area of business", is separate from table above and therefore not aligning properly.

**Comment by olehoef** [comment]
This section received a redesign that fixed the issue.
