### ISSUE TITLE
Logo, area of business etc

### ISSUE THREAD

**Issue by jazzjacob** [Systemvetardagen/systemvetardagen.se#239]
Create this part of the Company Page redesign.

See figma file "Company Page Wireframe" or talk to Jacob for more info.

![Image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/8ef1528d-a5ce-49da-8190-123c7c3fcf29)

**Comment by olehoef** [comment]
The changes look good!

I have just two small comment: 

1. The logo on mobile is a little to large.

<img width="342" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/9ab7b369-8843-4c49-9bdd-6df77ea36626">

2. I think it looks better if all logos have the same aspect ratio. 

<img width="759" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/65ad36f9-6556-41e3-a4df-2f956d140f75">

**Comment by jazzjacob** [comment]
I haven't looked into it in detail, but I agree with @olehoef's points

**Comment by amirhossein-haerian** [comment]
Thanks for the comments; I made some improvements. Would be happy to make more changes if needed.

**Comment by jazzjacob** [comment]
<img width="601" alt="Screenshot 2024-01-25 at 11 49 56" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/6c724a55-54d0-44ac-bd00-2775dec20263">

- Maybe try and use the same gray color in the text as you have made on the icons
- Extend line height to better match the figma
- Change to same font as in figma (I could fix this later as well)

**Comment by olehoef** [comment]
<img width="1221" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/d91f2c64-78e6-4648-bb3f-60f2db18c32f">
In the wide angle view it looks like this rn. Maybe put some gap in between? (not sure how it was intended to look @jazzjacob)

**Comment by jazzjacob** [comment]
Yeah it looks a bit squished in the middle there. I guess we didn't think about the cases with companies with little or no area of business when designing - this can be looked at later!!

**Comment by amirhossein-haerian** [comment]
Thanks for all the comments; some more improvements have been made based on the mentioned details, and now the code has been pushed.
