### ISSUE TITLE
Partner Image Gallery: Images have wrong size

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#295]
The left image should have the same height as the images on the right (combined). 

**Current:**
<img width="655" alt="Screenshot 2024-02-07 at 09 38 41" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/1648f482-42a7-42c0-b10e-9a09b9626c0b">

**Desired:**
<img width="397" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/4aa39109-5c4a-4cfd-a5d6-2635e54127de">

**Comment by amirhossein-haerian** [comment]
Image sizing issue in partner view is now fixed inside the partner-images-issue.
