### ISSUE TITLE
Image not loading on chrome

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#296]
Handelsbanken's 3rd partner gallery image is not loading on chrome. However, it loads on safari (after some time).

<img width="676" alt="Screenshot 2024-02-07 at 09 31 11" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/de52d30b-9f1f-42ca-acc6-9fae8a379e80">

**Comment by jazzjacob** [comment]
Fixed by changing image sizes in cms
