### ISSUE TITLE
Hide match list headings if no tags present

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#297]
It would look nicer if the headings wouldn't show if there are no tags.

<img width="863" alt="Screenshot 2024-02-07 at 09 32 17" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/ba487b8a-c74a-4f45-939f-787944f684b9">

**Comment by amirhossein-haerian** [comment]
The issue is now fixed inside the no_tags_issue branch.
