### ISSUE TITLE
Master programme filter not working

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#299]
Filtering for master programmes returns no companies although some companies have certainly selected this program.

<img width="832" alt="Screenshot 2024-02-07 at 09 34 45" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/01914407-920d-4818-9caa-5033fed2acde">

**Comment by olehoef** [comment]
@amirhossein-haerian  please make pull requests to the dev branch!

**Comment by amirhossein-haerian** [comment]
> @amirhossein-haerian please make pull requests to the dev branch!

It is done now.
