### ISSUE TITLE
Filter paragraph has no padding on mobile

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#300]
<img width="337" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/749d3d80-b396-4fc6-8c97-f0bc248712fe">

Either centre or add margin on left. Same goes for the search bar.

**Comment by amirhossein-haerian** [comment]
The padding is added to the catalog-padding branch.
