### ISSUE TITLE
Icons have large height in Safari

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#301]
**Safari:**
<img width="976" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/ecf91e6a-c19f-4384-929a-8ff65d58dd52">

**Chrome:**
<img width="977" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/109e03d7-6e88-450d-aa9d-d80c83df1380">

**Comment by jazzjacob** [comment]
Just adding what it should look like when collapsed.

**Safari:**
<img width="648" alt="Screenshot 2024-02-07 at 14 39 45" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/f1d67260-de29-4761-bf73-9faa0d7c322b">


**Chrome (correct):**
<img width="560" alt="Screenshot 2024-02-07 at 14 40 09" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/4993f53f-e6a9-4621-b043-07a6f84fcdba">
