### ISSUE TITLE
Programmes in front-end doesn't match CMS data

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#307]
See HiQ as example not sure if others have the same problem. 

<img width="655" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/c694a6a4-ae77-47a3-b129-9fbd6c52fc92">

<img width="714" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/15716b31-9e96-47e6-8937-18a60950c686">

Maybe the translations are not correctly pulled?

**Comment by amirhossein-haerian** [comment]
The fixed branch is, cms_ui_program_issue.
