### ISSUE TITLE
Banners in 1920x1080 too small

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#314]
<img width="769" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/b869553c-f3ec-4978-b742-7e1020f4ba95">

<img width="767" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/16816eb6-93c1-43d2-a603-9b50a04b6276">

How should we handle these?

**Comment by jazzjacob** [comment]
I think it's more of an eyesore that the about us page is no longer centered.

The banner size is less of an issue for me. The design idea requires the banners to stop growing at some point. So the easiest solution is probably if we just extend their max size or max width a bit

**Comment by olehoef** [comment]
<img width="321" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/39abcac4-fc4c-4bd1-aa5e-5fe437dd02b9">
Maybe allow 2 (or 3) columns of team members max and then centre the boxes (not the items).

**Comment by olehoef** [comment]
Problem got fixed.
