### ISSUE TITLE
Wrong alignment on safari

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#330]
**Safari (wrong):**
![image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/cb62847f-27da-49d8-ac95-9f2a2f256f94)

**Chrome (correct):**
<img width="968" alt="image" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/b5156842-7276-4043-b27a-0f64c9f0f72b">

I used text-wrap: nowrap; on the time column. Maybe that doesn't work on safari?

Also, the text should actually be aligned more on a centre line.

**Comment by jazzjacob** [comment]
Fixed with another issue
