### ISSUE TITLE
Finish "contact us" section

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#40]
- Finish the style implementation of the contact us section.
- Fix the js for the contact form. The code hasn't been moved over from the vanilla repo, so move it to this project (and preferably change the code to Vue syntax). The file is called form.js. Note that the request actually works, so don't spam the svd mail inbox 😄

**Comment by olehoef** [comment]
**Finished**
- contact form design
- functionality (no feedback yet if message actually arrives; positive alert is displayed though)

**Not Finished yet**
- Blob picture (I can't get it to show up)
- Submitting the form doesn't work with custom button yet. I might need to add @click functionality to the button component.

**Comment by olehoef** [comment]
No, it's even easier. I just did @click.native='submit'.

**Comment by olehoef** [comment]
**Updated current progress**

**Not finished yet:**

- click hand when you hover the btn
- blob picture
- SV translation
- paddings (best to implement once the picture is there)
- btn width (I first need to merge with another branch)
- backend: the message don't end up in the email

**Comment by olehoef** [comment]
**Updated current progress**

**Not finished yet:**

- click hand when you hover the btn
- SV translation
- backend: the message don't end up in the email

I have hidden the blob on mobile view (screen size < 1024) because I could not get it to work. This shouldn't be our prio rn, I think.

**Comment by olehoef** [comment]
Can you add the swedish translations?

Also, I was thinking, maybe the server sending the email checks from which site the request is coming. Since in my case it's local host, maybe that's the problem? Does the vanilla version work in a dev environment?

**Comment by olehoef** [comment]
**Regarding the Backend:**

- I have checked the server response when sending the JSON file to the link and it is 200 = OK
- According to some small research I have done it looks like you're using a workers server from cloudflare. Is that correct? Also, based on what I can see, there should be some kind of backend service you can log in to. I have also found shell commands to access the server's system log, but I have no clue where to type them in. Maybe we have to install something in our web application? But, on the other hand, I didn't see anything like that in the vanilla code. If you can't get access to any backend, we could try to compare the http headers (between the old website and the new) and see if we can spot some differences.

**Comment by j-wiren** [comment]
Translation:
Heading: "Kontakta oss"
Name / Namn
E-mail / E-mail
Company / Företag
Message / Meddelande
Send / Skicka
