### ISSUE TITLE
Fix mobile navbar button

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#42]
The mobile navbar button (hamburger icon) doesn't work in this project. The js file hasn't been moved over from the old project (vanilla). Take that one, [link here](https://github.com/Systemvetardagen/systemvetardagen-vanilla/blob/main/nav.js), change it to vue syntax and make it work.

**Comment by aakruti27** [comment]
This works functioning-wise but needs to display the options neatly as a sidebar. https://github.com/Systemvetardagen/systemvetardagen.se/tree/navjs-AM  (@olehoef )
