### ISSUE TITLE
Landing_oldCatalog implement old catalog

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#49]
- replace placeholder with 2022 catalog cover
- link 2022 catalog

@j-wiren are we still using yumpu or how will it work?

**Comment by olehoef** [comment]
**Updated to-do's**

- link 2022 catalog

**Comment by j-wiren** [comment]
New to-do
- Make the link download the catalog as a PDF (catalog is just in Swedish)
- Button title: "Download catalog 2022" / "Ladda ner katalogen 2022"
- Fix positioning for mobile and desktop

**Comment by olehoef** [comment]
**Nuxt Link issue**

I found this simple HTML solution to download pdfs with a tags:
`<a href="@/assets/img/SvD-2022-catalog.pdf" download="Systemvetardagen 2022 Katalog"> Get cat</a>`

However, I'm just getting these errors:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/81076759/215271189-1474f1ac-01c9-4974-bdde-9fed275ac127.png">

I think the link is not correct. If you for example link an image, the output element links to "/_nuxt/....

**Comment by olehoef** [comment]
Do we still want to do this. Or did we kill this feature?
