### ISSUE TITLE
Fix font loading on site load

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#57]
With this project we load fonts locally, as opposed to just importing them from google fonts or something. But when loading them locally the site loads before the fonts are done loading, and it results in an ugly preview with Times New Roman (or the browser default) until the fonts have loaded.

- I know you can change so that the site waits until the fonts have loaded before it shows the site. Find out how to do that and implement it. 
- If it takes too long for the fonts to load you can also change the font rendering properties with CSS, to use a less heavy font rendering.

**Comment by j-wiren** [comment]
If we add sans-serif to the end of the font-family property in the main.css file it should be okay for now.

**Comment by aakruti27** [comment]
[This branch](https://github.com/Systemvetardagen/systemvetardagen.se/tree/navjs-AM) has font-display: block as well as the sans-serif fonts added to the fonts list.

It works, but only for some buttons, nav text and contact us form. Does not necessarily work for all text of the website.

**Comment by olehoef** [comment]
Is this issue fixed?
