### ISSUE TITLE
Add section for StudentNode

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#60]
We need to add an informational section about StudentNode, the service we use for booking meetings with companies.

**Comment by j-wiren** [comment]
I'll write the text and send it to you. 
What to include:
- Screenshot of the site (something that looks nice and gives a sense of what it is)
- Heading: Book interviews with the companies (or something). Will send that as well
- Info text (that I'll send)
- Button with a link to the site - mitt.systemvetardagen.se

**Comment by aakruti27** [comment]
[Student Node Section](https://github.com/Systemvetardagen/systemvetardagen.se/tree/student-node-AM) added. 

-No pictures yet
-No button yet, the "go to  mitt.systemvetardagen,se" step has the link included for now. 
-SV text needed 
-confirm position of this section??
