### ISSUE TITLE
Node.js version warning

### ISSUE THREAD

**Issue by yizhouyang999** [Systemvetardagen/systemvetardagen.se#8]
The latest Node.js(19.1.0) will cause crash of our project in windows. (16.18.1) is working fine in Linux.

**Comment by jolofren** [comment]
Yes, with Node we have to stay with a specific version and not update it, in order for it to work with the project dependencies.

So if anyone is having problems with Node version you can downgrade to 16.18.

If you're working on other Node projects that require a different version there are tools you can install to manage different Node versions.
