### ISSUE TITLE
Finalize simple catalog page

### ISSUE THREAD

**Issue by j-wiren** [Systemvetardagen/systemvetardagen.se#87]
The catalog needs to go live ASAP, so for the company page the focus is to get all the information on the page in an acceptably presentable way.
- Follow the design for the sponsor page, since that one has all the info.
- Use v-if statements for the sponsor content if it's available or not.
- Create youtube embed from sponsor youtube link

**Comment by olehoef** [comment]
All the content is now on the page. Next step is to implement the design.
